### ISSUE TITLE
Explore better exporting

### ISSUE THREAD

**Issue by bmann** [Causal-Islands/toronto-2023#2]
I have the CSV files from the CMS exported, ideally want to find other ways to have the full site exported statically.

If you've done Webflow CMS -> Static HTML, please do make suggestions.

**Comment by bmann** [comment]
Do I trust a random web extension? https://udesly.nexus/pages/webflow-to-jamstack

**Comment by bmann** [comment]
Tried it, doesn't get the CMS content either.

**Comment by iepn** [comment]
> Tried it, doesn't get the CMS content either.

https://www.udesly.com/

The content I found on [Reddit](https://www.reddit.com/r/webflow/comments/s2mgnj/exporting_a_website_while_keeping_cms/) might be useful.

**Comment by iusx** [comment]
https://answers.netlify.com/t/support-guide-how-to-migrate-from-webflow-to-netlify-create/109391

The content I found on netlify might be useful.

**Comment by bmann** [comment]
Thanks @iepn -- the hard part is the CMS content. I have the data sources and have transformed the site to Jekyll. Going to start a new issue with the remaining work to do.
